apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://raw.githubusercontent.com/argoproj/argo-cd/v2.7.2/manifests/install.yaml
patches:
- patch: |-
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: argocd-cm
      labels:
        app.kubernetes.io/name: argocd-cm
        app.kubernetes.io/part-of: argocd
    data:
      users.anonymous.enabled: "true"
      resource.links: |
        - url: http://localhost:9001/oci/details?clusterName=Default&name={{.metadata.name}}&namespace={{.metadata.namespace}}
          title: "Weave GitOps"
          if: kind == "OCIRepository"
        - url: http://localhost:9001/git_repo/details?clusterName=Default&name={{.metadata.name}}&namespace={{.metadata.namespace}}
          title: "Weave GitOps"
          if: kind == "GitRepository"
        - url: http://localhost:9001/bucket/details?clusterName=Default&name={{.metadata.name}}&namespace={{.metadata.namespace}}
          title: "Weave GitOps"
          if: kind == "Bucket"
        - url: http://localhost:9001/helm_chart/details?clusterName=Default&name={{.metadata.name}}&namespace={{.metadata.namespace}}
          title: "Weave GitOps"
          if: kind == "HelmChart"
        - url: http://localhost:9001/kustomization/details?clusterName=Default&name={{.metadata.name}}&namespace={{.metadata.namespace}}
          title: "Weave GitOps"
          if: kind == "Kustomization"
        - url: http://localhost:9001/helm_release/details?clusterName=Default&name={{.metadata.name}}&namespace={{.metadata.namespace}}
          title: "Weave GitOps"
          if: kind == "HelmRelease"
        - url: http://localhost:9001/terraform_object/details?clusterName=Default&name={{.metadata.name}}&namespace={{.metadata.namespace}}
          title: "Weave GitOps"
          if: kind == "Terraform"
  target:
    kind: ConfigMap
    name: argocd-cm
- patch: |-
    apiVersion: v1
    kind: ConfigMap
    metadata:
      labels:
        app.kubernetes.io/name: argocd-rbac-cm
        app.kubernetes.io/part-of: argocd
      name: argocd-rbac-cm
    data:
      policy.default: role:readonly
      policy.csv: |
        p, role:readonly, applications, get, default/*, allow
        p, role:readonly, applications, sync, default/*, allow
        p, role:readonly, clusters, get, *, allow
        p, role:readonly, repositories, get, *, allow
        p, role:readonly, project, get, default/*, allow
  target:
    kind: ConfigMap
    name: argocd-rbac-cm
images:
- name: quay.io/argoproj/argocd:v2.7.2
  newName: ghcr.io/flux-subsystem-argo/fsa/argocd
  newTag: v2.7.2-fl.6-main-fa20ba74