apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.4.13/manifests/install.yaml
images:
  - name: quay.io/argoproj/argocd:v2.4.13
    newName: ghcr.io/flux-subsystem-argo/fsa/argocd
    newTag: v2.4.13-fl.2-main-016c20e9
